### ISSUE TITLE
Exception raised when creating code editor widget

### ISSUE THREAD

**Issue by twizmwazin** [angr/pyqodeng#5]
### Description

I think this is related to the Pyside 6.4 enum changes.

```
Traceback (most recent call last):
  File "start.py", line 7, in <module>
    main()
  File "angrmanagement/__main__.py", line 248, in main
    start_management(args.binary,
  File "angrmanagement/__main__.py", line 185, in start_management
    main_window = MainWindow(app=app, use_daemon=use_daemon)
  File "angrmanagement/ui/main_window.py", line 98, in __init__
    self._init_workspace()
  File "angrmanagement/ui/main_window.py", line 250, in _init_workspace
    wk = Workspace(self, Instance())
  File "angrmanagement/ui/workspace.py", line 65, in __init__
    CodeView(self._main_instance, 'center'),
  File "angrmanagement/ui/views/code_view.py", line 54, in __init__
    self._init_widgets()
  File "angrmanagement/ui/views/code_view.py", line 422, in _init_widgets
    self._textedit = QCCodeEdit(self)
  File "angrmanagement/ui/widgets/qccode_edit.py", line 49, in __init__
    super().__init__(create_default_actions=True)
  File "pyqodeng/core/api/code_edit.py", line 498, in __init__
  File "pyqodeng/core/api/code_edit.py", line 1273, in _init_actions
TypeError: unsupported operand type(s) for |: 'KeyboardModifier' and 'Key'
```

### Steps to reproduce the bug

Run angr management nightly pipeline

### Environment

Occurred in angr management nightly pipeline on Ubuntu 20.04 and 22.04, pyinstaller builds

**Comment by mborgerson** [comment]
Fixed in a71a2fba9099358fb64a62c5e370a5c5ecf4e271
